<?php 
return array (
 'banner_body'=>array(
   '<li style="position: absolute; display: none;"><div class="a1-1" style="left: 700px; opacity: 1; display: block; top: 140px;"></div><div class="a1-2" style="left: 120px; opacity: 1; display: block; top: 180px;"><strong style="font-weight:bold">'.C('site_name').'</strong>，产品营销推广专家</div><div class="a1-3" style="left: 120px; opacity: 1; display: block; top: 240px;">                    国内唯一一家专注产品营销推广<br />                    免费自主创作高品质HTML5移动页面的专业平台<br />                    结合社会化媒体快速裂变，开启全网联动互动营销时代。<br /><div style="line-height:10px; height:10px; display:block"></div><span style="border:none;border-bottom:1px solid #b294a3; border-top:1px solid #b294a3; line-height:50px; display:block; width:400px; "><b id="scenecount">1</b><span>个产品正在使用'.C('site_name').'！</span></span></div><div class="a1-4"  ng-click="openRegister()" style="left: 120px; opacity: 1; display: block; top: 420px;"></div></li>',
   '<li style="position: absolute; display: none;"><div class="a3-1">适用&nbsp;&nbsp;&nbsp;实用&nbsp;&nbsp;&nbsp;简便</div><div class="a3-2">为各行各业提供百亿级产品服务</div><div class="a3-3">                    产品推广、品牌展示、活动宣传、会议举办</br>                    产品说明书、在线购买、售后服务、生产追溯、渠道跟踪</br></div><div class="a3-4"><img src="/index/images/88cb8d6b62dbf041.png" /></div></li>',
   '<li style="position: absolute; display: list-item;"><div class="a2-1">让每一个<strong>产品</strong>都有自己的<strong>故事</strong></div><div class="a2-2"><div style="font-size:36px; line-height:40px; color:#4aa318">我们的故事已经开启，你们的呢？</div></div><div class="a2-6"><div style="line-height:30px; font-size:16px; margin-top:20px;">                        我们怀揣梦想/我们追求极致/我们传递信仰<br>                        我们梦想助力所有企业更快融入移动互联网，于是，'.C('site_name').'来了！<br /></div></div><div class="a2-7" onClick="document.location=\'#/home/register\';" style="top: 400px; opacity: 1; display: block; left: 450px;"></div></li>',
   '<li style="position: absolute; display: none;"><div class="a4-1">超级产品秀</div><div class="a4-2"><img src="/index/images/0c27f8485afb152a.png" /></div><div class="a4-3"></div><a class="a4-4" target="_blank" href="/"</a><a class="a4-5" target="_blank" href="/" ></a></li>',
  '<li style="position: absolute; display: none;"><div class="a5-1">放肆吐槽&nbsp;&nbsp;人人都是产品经理</div><div class="a5-2">'.C('site_name').'，你来作主！有奖，快来！</div><a class="a5-3" target="_blank" href="/"></a></li>',
  '<li style="position: absolute; display: none;"><div class="a6-1">您的每一次咨询&nbsp;&nbsp;我们都倍感珍贵</div><div class="a6-3">                    '.C('site_name').'拥有完善的客服团队，官方客服电话、官方QQ群、交流论坛</br>                    您的声音在哪里，我们就在哪里</br></div><div class="a6-4"><img src="/index/images/slider-61.png" /></div></li>' 
   
 )
  
);