<?php
$dllist = Array
(
    0 => 'install.class.php',
    1 => 'dllist.php',
    2 => 'file/app/app/branchmap/admin/ajax.class.php',
    3 => 'file/app/app/branchmap/admin/config.class.php',
    4 => 'file/app/app/branchmap/admin/info_off.class.php',
    5 => 'file/app/app/branchmap/admin/info_on.class.php',
    6 => 'file/app/app/branchmap/admin/table_ajax.class.php',
    7 => 'file/app/app/branchmap/admin/table_off.class.php',
    8 => 'file/app/app/branchmap/admin/table_on.class.php',
    9 => 'file/app/app/branchmap/admin/templates/config.php',
    10 => 'file/app/app/branchmap/admin/templates/info.php',
    11 => 'file/app/app/branchmap/admin/templates/js/configmap.js',
    12 => 'file/app/app/branchmap/admin/templates/js/func.js',
    13 => 'file/app/app/branchmap/admin/templates/js/infomap.js',
    14 => 'file/app/app/branchmap/admin/templates/js/own.js',
    15 => 'file/app/app/branchmap/admin/templates/table.php',
    16 => 'file/app/app/branchmap/admin/uninstall.class.php',
    17 => 'file/app/app/branchmap/icon.png',
    18 => 'file/app/app/branchmap/include/class/appadmin.class.php',
    19 => 'file/app/app/branchmap/include/class/appweb.class.php',
    20 => 'file/app/app/branchmap/include/class/cloud.class.php',
    21 => 'file/app/app/branchmap/lang/branchmap.sql',
    22 => 'file/app/app/branchmap/lang/cn.php',
    23 => 'file/app/app/branchmap/lang/en.php',
    24 => 'file/app/app/branchmap/lang/tc.php',
    25 => 'file/app/app/branchmap/lang/update1.3.sql',
    26 => 'file/app/app/branchmap/plugin/plugin_branchmap.class.php',
    27 => 'file/app/app/branchmap/select-linkage/city.min.js',
    28 => 'file/app/app/branchmap/select-linkage/jquery.cityselect.js',
    29 => 'file/app/app/branchmap/web/index.class.php',
    30 => 'file/app/app/branchmap/web/templates/css/branchmap.css',
    31 => 'file/app/app/branchmap/web/templates/css/yunwang.bootstrap.min.css',
    32 => 'file/app/app/branchmap/web/templates/index.php',
    33 => 'file/app/app/branchmap/web/templates/js/common.js',
    34 => 'file/app/app/branchmap/web/templates/js/jquery/1.11.1/jquery.js',
    35 => 'file/app/app/branchmap/web/templates/js/jquery/1.11.1/jquery_seajs.js',
    36 => 'file/app/app/branchmap/web/templates/js/own.js',
    37 => 'file/app/app/branchmap/web/templates/js/sea.v1.js',
    38 => 'file/app/app/branchmap/web/templates/js/sea2.2.1.js',
);
?>